Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
Documentation:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
